# Generated by Django 3.1 on 2021-05-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(default=None, max_length=100)),
                ('questDur', models.DurationField()),
            ],
        ),
        migrations.RemoveField(
            model_name='interviews',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='interviews',
            name='questDur',
        ),
        migrations.RemoveField(
            model_name='interviews',
            name='question',
        ),
        migrations.AddField(
            model_name='companies',
            name='phoneNo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewees',
            name='IntervieweeEmail',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='interviews',
            name='Title',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='interviews',
            name='questions',
            field=models.ManyToManyField(to='interviewers.Questions'),
        ),
    ]
