# Generated by Django 3.1 on 2021-05-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviewers', '0004_auto_20210523_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviews',
            old_name='Title',
            new_name='title',
        ),
    ]
