# Generated by Django 3.1 on 2021-07-07 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviewers', '0005_auto_20210523_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntervQuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervQuest', to='interviewers.interviews')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervQuest', to='interviewers.questions')),
            ],
        ),
    ]
