# Generated by Django 3.1 on 2021-07-07 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviewers', '0006_intervquest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intervquest',
            options={'ordering': ['order']},
        ),
    ]
