# Generated by Django 3.1 on 2021-07-07 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviewers', '0007_auto_20210707_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviews',
            name='questions',
        ),
    ]
