# Generated by Django 3.1 on 2021-07-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewers', '0010_remove_interviews_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervquest',
            name='interview',
        ),
        migrations.AddField(
            model_name='intervquest',
            name='interview',
            field=models.ManyToManyField(to='interviewers.Interviews'),
        ),
        migrations.RemoveField(
            model_name='intervquest',
            name='question',
        ),
        migrations.AddField(
            model_name='intervquest',
            name='question',
            field=models.ManyToManyField(to='interviewers.Questions'),
        ),
    ]
