# Generated by Django 3.1 on 2021-07-07 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviewers', '0011_auto_20210707_1813'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IntervQuest',
        ),
    ]
