# Generated by Django 3.1 on 2021-07-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewers', '0013_interviewquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviews',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='questions',
            name='skills',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
