# Generated by Django 3.1 on 2021-07-13 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviewers', '0014_auto_20210713_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='waiting', max_length=100)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='interviewers.interviews')),
            ],
        ),
        migrations.RenameField(
            model_name='interviewees',
            old_name='IntervieweeEmail',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='interviewees',
            name='interview',
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(default='', max_length=500)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='interviewers.applicants')),
            ],
        ),
        migrations.AddField(
            model_name='applicants',
            name='interviewee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='interviewers.interviewees'),
        ),
    ]
