# Generated by Django 3.1 on 2021-07-13 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interviewers', '0015_auto_20210713_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewees',
            name='send_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='interviewee_send_by', to='auth.user'),
            preserve_default=False,
        ),
    ]
