# Generated by Django 3.1 on 2021-07-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewers', '0016_interviewees_send_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='invitationLink',
            field=models.CharField(default='', max_length=300),
        ),
    ]
