# Generated by Django 3.1 on 2021-07-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewers', '0018_auto_20210716_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewees',
            name='state',
            field=models.CharField(default='Waiting', max_length=100),
        ),
    ]
