# Generated by Django 3.1 on 2021-07-18 19:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviewers', '0020_questions_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviews',
            name='Expiration_date',
            field=models.DateTimeField(default=datetime.date(2021, 7, 21)),
        ),
        migrations.AlterField(
            model_name='questions',
            name='questDur',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.CreateModel(
            name='ApplicantQues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoAns', models.CharField(default='', max_length=500)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appQues', to='interviewers.applicants')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appQues', to='interviewers.questions')),
            ],
        ),
    ]
